# Generated by Django 4.1.7 on 2023-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
