# Generated by Django 4.1.7 on 2023-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patientform_age_alter_patientform_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='bloodgrp',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
