# Generated by Django 4.1.7 on 2023-04-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientform_pusername_alter_patientform_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='allergy',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='bloodgrp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='drughistory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='goingonMedications',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='insurance',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='medicalhistory',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='pemail',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='pusername',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='symptoms',
            field=models.CharField(default='', max_length=100),
        ),
    ]
