# Generated by Django 4.1.7 on 2023-04-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patientform_allergy_alter_patientform_bloodgrp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientform',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='bloodgrp',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='gender',
        ),
    ]
