# Generated by Django 4.1.7 on 2023-04-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_patientform_allergy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientform',
            name='allergy',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patientform',
            name='bloodgrp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patientform',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
    ]
