# Generated by Django 4.1.7 on 2023-04-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patientform_allergy_patientform_bloodgrp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientform',
            name='state',
        ),
    ]
