# Generated by Django 4.1.7 on 2023-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_patientform_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientform',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
