# Generated by Django 4.1.7 on 2023-04-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patientform_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='bloodgrp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
