# Generated by Django 4.1.7 on 2023-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_patientform_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientform',
            name='drughistory',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='fname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='insurance',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='lname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='medicalhistory',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='symptoms',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
