# Generated by Django 4.1.7 on 2023-04-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_patientform_drughistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Unapproved', max_length=20, null=True)),
                ('patientdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientform')),
            ],
        ),
    ]
