# Generated by Django 4.1.7 on 2023-04-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
