# Generated by Django 4.1.7 on 2023-04-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_booking_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='patientdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patientform'),
        ),
    ]
