# Generated by Django 4.1.7 on 2023-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_alter_booking_patientdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pusername',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
