# Generated by Django 4.1.7 on 2023-04-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_booking_pusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pfname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
