# Generated by Django 4.1.7 on 2023-04-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_booking_pfname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingid',
            field=models.IntegerField(null=True),
        ),
    ]
