# Generated by Django 4.1.7 on 2023-04-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_booking_bookingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
