# Generated by Django 4.1.7 on 2023-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_booking_date_booking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='auto_field',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
