# Generated by Django 4.1.7 on 2023-04-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_alter_booking_auto_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='auto_field',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
