# Generated by Django 4.1.7 on 2023-04-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_alter_booking_auto_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='auto_field',
        ),
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
