# Generated by Django 4.1.7 on 2023-04-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_remove_booking_auto_field_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='auto_field',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingid',
            field=models.IntegerField(null=True),
        ),
    ]
