# Generated by Django 4.1.7 on 2023-04-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_remove_booking_auto_field_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='patientdetail',
        ),
    ]
