# Generated by Django 4.1.7 on 2023-04-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0028_remove_booking_bookingid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='auto_field',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='patientdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patientform'),
        ),
    ]
