# Generated by Django 4.1.7 on 2023-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0029_booking_auto_field_booking_bookingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='auto_field',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
