# Generated by Django 4.1.7 on 2023-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0033_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='datewise_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('updatedSlotdict', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='slotNum',
            field=models.IntegerField(null=True),
        ),
    ]
