# Generated by Django 4.1.7 on 2023-04-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0035_datewise_slot_doc_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datewise_slot',
            name='updatedSlotdict',
            field=models.JSONField(null=True),
        ),
    ]
