# Generated by Django 4.1.7 on 2023-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0036_alter_datewise_slot_updatedslotdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datewise_slot',
            name='updatedSlotdict',
        ),
        migrations.AddField(
            model_name='datewise_slot',
            name='evening_updatedSlotdict',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='datewise_slot',
            name='morning_updatedSlotdict',
            field=models.JSONField(default=None, null=True),
        ),
    ]
