# Generated by Django 4.1.7 on 2023-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0037_remove_datewise_slot_updatedslotdict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
