# Generated by Django 4.1.7 on 2023-04-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0038_booking_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='lname',
            new_name='plname',
        ),
    ]
