# Generated by Django 4.1.7 on 2023-04-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0039_rename_lname_booking_plname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientform',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='dusername',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patientform',
            name='slot',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientform',
            name='slotNum',
            field=models.IntegerField(null=True),
        ),
    ]
