# Generated by Django 4.1.7 on 2023-04-03 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dusername', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('image', models.ImageField(default='', upload_to='doctor/images')),
                ('specialization', models.CharField(max_length=100)),
                ('specdegree', models.FileField(default='', upload_to='doctor/files')),
                ('license', models.FileField(default='', upload_to='doctor/files')),
                ('fromtime', models.CharField(max_length=5)),
                ('totime', models.CharField(max_length=5)),
                ('avgtime', models.CharField(max_length=20)),
                ('housenum', models.CharField(max_length=75)),
                ('hcity', models.CharField(max_length=20)),
                ('hlandmark', models.CharField(max_length=50)),
                ('hzip', models.IntegerField(default=0)),
                ('hstate', models.CharField(max_length=50)),
                ('clocation', models.CharField(max_length=75)),
                ('ccity', models.CharField(max_length=20)),
                ('clandmark', models.CharField(max_length=50)),
                ('czip', models.IntegerField(default=0)),
                ('cstate', models.CharField(max_length=50)),
                ('duser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
