# Generated by Django 4.1.7 on 2023-04-03 05:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor',
            new_name='doctordetails',
        ),
    ]
