# Generated by Django 4.1.7 on 2023-04-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctordetail_avgtime_alter_doctordetail_ccity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetail',
            name='clandmark',
        ),
    ]
