# Generated by Django 4.1.7 on 2023-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctordetail_clandmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='avgtime',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='ccity',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='clocation',
            field=models.CharField(default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='cstate',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='czip',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='fromtime',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='hcity',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='hlandmark',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='housenum',
            field=models.CharField(default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='hstate',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='hzip',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='doctor/images'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='license',
            field=models.FileField(default='', null=True, upload_to='doctor/files'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='specdegree',
            field=models.FileField(default='', null=True, upload_to='doctor/files'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='specialization',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='totime',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
