# Generated by Django 4.1.7 on 2023-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctordetail_avgtime_alter_doctordetail_ccity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='doctor/images'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='license',
            field=models.FileField(default=None, null=True, upload_to='doctor/files'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='specdegree',
            field=models.FileField(default=None, null=True, upload_to='doctor/files'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='specialization',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
