# Generated by Django 4.1.7 on 2023-04-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_doctordetail_avgtime_alter_doctordetail_ccity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='license',
            field=models.FileField(default='', null=True, upload_to='doctor/files'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='specdegree',
            field=models.FileField(default='', null=True, upload_to='doctor/files'),
        ),
    ]
