# Generated by Django 4.1.7 on 2023-04-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_doctordetail_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetail',
            name='duser',
        ),
    ]
