# Generated by Django 4.1.7 on 2023-04-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_doctordetail_duser'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetail',
            name='desc',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
