# Generated by Django 4.1.7 on 2023-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_alter_doctordetail_fname_alter_doctordetail_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_username', models.CharField(max_length=50, null=True)),
                ('slotDict', models.CharField(default='', max_length=500, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
