# Generated by Django 4.1.7 on 2023-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slotDict',
            field=models.JSONField(),
        ),
    ]
