# Generated by Django 4.1.7 on 2023-04-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_slot_slotdict'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='slot',
            new_name='slot_table',
        ),
    ]
