# Generated by Django 4.1.7 on 2023-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_slot_table_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot_table',
            name='slotDict',
        ),
        migrations.AddField(
            model_name='slot_table',
            name='eveningslotDict',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='slot_table',
            name='morningslotDict',
            field=models.JSONField(default=None, null=True),
        ),
    ]
