# Generated by Django 4.1.7 on 2023-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_remove_slot_table_slotdict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetail',
            name='eveningfromtime',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='doctordetail',
            name='eveningtotime',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
