# Generated by Django 4.1.7 on 2023-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_doctordetail_eveningfromtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetail',
            name='shortdesc',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
